### ISSUE TITLE
@x-ray/native-screenshots-app wasn't released after bumping react-native to 0.63.4

### ISSUE THREAD

**Issue by irminakacz** [nextools/metarepo#235]
Hi 👋
While upgrading react-native in my project from 0.63.2 to 0.63.4 I noticed that `@x-ray/native-screenshots-app` still uses version 0.63.2 of react-native, although all other @x-ray plugins & packages already use version 0.63.4.
It seems that `@x-ray/native-screenshots-app` had react-native updated in it's package.json, but it doesn't seem that it was released after that.
I double checked by downloading the zip of `@x-ray/native-screenshots-app` v4.0.0 and it still has react-native on 0.63.3 in it's package.json.
Could you please bump the package and release it? 🙂

**Comment by deepsweet** [comment]
`@x-ray/native-screenshots-app@4.0.1`
