### ISSUE TITLE
Package path ./dist/sha1 is not exported from package

### ISSUE THREAD

**Issue by irminakacz** [nextools/metarepo#237]
Hi 👋 
While updating dependencies in my project I noticed that after package `jssha` (that is used inside `autoprops`) is bumped to latest version (v3.2.0) it throws an error when trying to run react-native snapshots.
I'm also getting the same error after upgrading and trying to run react-native snapshots in nextools/metarepo:
```
checkReactNativeSnapshots.x-ray: Package path ./dist/sha1 is not exported from package /Users/irminakacz/metarepo/node_modules/jssha (see exports field in /Users/irminakacz/metarepo/node_modules/jssha/package.json)
checkReactNativeSnapshots.x-ray: error
checkReactNativeSnapshots.sequence: error
error Command failed with exit code 1.
```

After some investigation it seems that it is this change in the `jssha` package that is causing it: https://github.com/Caligatio/jsSHA/commit/e033f3d5a59ce41f3ed9f2303535c56d9000aacc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
After using the previous version of `package.json` the react-native snapshots run just fine.
Do you think it's something that could be fixed on our side or is it strictly an issue that needs to be solved inside `jssha` package?

I was testing it on node v14.15.4

**Comment by deepsweet** [comment]
Fixed with `autoprops@4.0.2`
