### ISSUE TITLE
auto tries to publish new packages with old commits

### ISSUE THREAD

**Issue by moriaam** [nextools/metarepo#243]
Hey!

We have an old commit in our library which has been published: `🐞 *: bump foo`
Because of the asterisk (even though it was already published), when adding new packages to the monorepo, after running `yarn start testPublish` it suggests to publish the new packages with this commit:
```
@new-package → patch → v0.0.1
* 🐞 bump foo

? Looks good? › - Use arrow-keys. Return to submit.
❯   no
    yes
```

how can we change it so it won't bump new packages?

**Comment by deepsweet** [comment]
Make sure that the initial commit has the right emoji _and_ message.

**Comment by moriaam** [comment]
The problem is we're moving existing packages, so they're not actually new initialized packages :/

**Comment by deepsweet** [comment]
`auto` needs either a "publish" or "initial" type commit to stop traversing down through Git history, because a package can't appear out of nowhere, there should be some valid start point.

**Comment by deepsweet** [comment]
"moved" (I assume you've just renamed some?) package should start with the same initial `0.0.0` version and initial commit as well.

**Comment by moriaam** [comment]
We moved existing packages that are already published from a different branch to the master branch.
We'll republish them with initial then.
Thanks for the help & the solution :)
