### ISSUE TITLE
@rebox supporting `react-native-svg` on Xcode 12

### ISSUE THREAD

**Issue by irminakacz** [nextools/metarepo#260]
Hi 👋
I was trying to use @rebox on Xcode 12.4 with additional dependency `react-native-svg`, but it was resulting in this error:
```
The following build commands failed:
        Ld /Users/user.name/Library/Developer/Xcode/DerivedData/rebox-byjvpkhoayqrwpfsuipmqmyqgpzv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/Binary/RNSVG normal x86_64
(1 failure)
```

After some research, I found that this specific fix seems to work:
https://github.com/react-native-svg/react-native-svg/issues/1510
(replacing 'React' with 'React-Core' inside `./node_modules/react-native-svg/RNSVG.podspec`)

So far I'm using it by adding a simple postinstall script in my project:
```
  "scripts": {
    "postinstall": "sed -i '' \"s/'React'/'React-Core'/\" ./node_modules/react-native-svg/RNSVG.podspec"
  },

```

My question is: Do you think it makes sense and if it's possible to have a fix inside rebox?
I've seen more people having similar issues with different dependencies,
 but I didn't manage to get their proposed solution to work rebox: facebook/react-native#29633

**Comment by irminakacz** [comment]
After testing it in pipeline it seems that this `sed` command fails for linux, but perl seems to work just fine :)
```
 "scripts": {
    "postinstall": "perl -pi -e \"s/'React'/'React-Core'/g\" ./node_modules/react-native-svg/RNSVG.podspec"
  },
```

**Comment by deepsweet** [comment]
hi!

`react-native-svg` dependency is not a built-in part of `rebox` anymore, therefore we can't monkey-patch every single 3rd-party dependency because it's up to a user-land now.

as per facebook/react-native#29633:

>The correct fix going forward is for all these libs to update their dependency from React to React-Core

I think the only solution until it's not fixed by `react-native-svg` authors would be to patch it from your side.
