### ISSUE TITLE
🐞 Redux store type error in refun StoreContextFactory with redux > 3.0.0

### ISSUE THREAD

**Issue by xaviervia** [nextools/metarepo#51]
Redux ^2.0.0, no problem:

<img width="954" alt="Screen Shot 2020-04-20 at 07 20 53" src="https://user-images.githubusercontent.com/381614/79716682-bc7b5400-82d7-11ea-9f02-0fcba71f8d5b.png">
<img width="942" alt="Screen Shot 2020-04-20 at 07 21 00" src="https://user-images.githubusercontent.com/381614/79716684-bd13ea80-82d7-11ea-8c17-59cd8f119059.png">

Redux ^3.0.0 or ^4.0.0, 💥:
<img width="961" alt="Screen Shot 2020-04-20 at 07 21 44" src="https://user-images.githubusercontent.com/381614/79716720-dc127c80-82d7-11ea-9183-630b349fbab7.png">

It's not much of a problem since using Redux 2.x circumvents it, but surprising when trying to debug the error.

**Comment by deepsweet** [comment]
can't reproduce anymore, seems to be fixed already.
