### ISSUE TITLE
Trying to learn how to use @start

### ISSUE THREAD

**Issue by lifeiscontent** [nextools/metarepo#8]
@deepsweet first of all, thank you.

I've spent the last 3 days dealing with build system issues trying to get my UI Framework up and running.

I've got a semi-complicated build using typescript and a babel macro and I haven't been able to get it to compile using rollup, webpack or gulp.

would you have some time to either write a start preset for me or teach me how to use start?

In return, I'd be willing to write documentation or help on some issues if needed.

**Comment by deepsweet** [comment]
Hi.

I'm ready to help as much as I can. The easiest way to help you is to have some repository to play with. Could you please provide that and also explain your difficulties in more details?

**Comment by lifeiscontent** [comment]
@deepsweet great, thanks so much! I've invited you to the repo. the preset I've setup in the monorepo is called 'start-preset' if you use discord or something, we can chat. Otherwise if you have any direct questions about the code, feel free to just open up an issue on GitHub.

**Comment by deepsweet** [comment]
any chance you have Telegram? https://t.me/deepsweet

**Comment by lifeiscontent** [comment]
@deepsweet messaged you!

**Comment by deepsweet** [comment]
closing the issue because we are in touch already.
