### ISSUE TITLE
Wrong Type used for typescript plugin

### ISSUE THREAD

**Issue by lifeiscontent** [nextools/metarepo#9]
the typescript options for start-plugin-typescript are a bit confusing.

in order to make my config work I had to set it up like this:

```ts
const typescriptConfig: ts.CompilerOptions = {
  allowSyntheticDefaultImports: true,
  lib: ['lib.dom.d.ts', 'lib.esnext.d.ts'],
  target: ts.ScriptTarget.ESNext,
  moduleResolution: ts.ModuleResolutionKind.NodeJs,
  jsx: ts.JsxEmit.Preserve,
};
```

I think a better UX, if possible is to map it to the tsconfig options.

**Comment by deepsweet** [comment]
Hi!

Thanks, we'll take a look, it definitely should work with strings just like in `tsconfig.json`.

**Comment by deepsweet** [comment]
[fixed](https://github.com/nextools/metarepo/blob/master/packages/start/plugin-lib-typescript-generate/changelog.md)
